allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  '@prisma/engines': true
  '@tsparticles/engine': true
  esbuild: true
  prisma: true
  protobufjs: true
  puppeteer: true
  re2: true
  unrs-resolver: true
